import {
    Activity,
    Award,
    BookOpen,
    Bookmark,
    Briefcase,
    CalendarCheck,
    CalendarDays,
    CalendarRange,
    Crown,
    GitBranch,
    Globe,
    Hexagon,
    Laptop,
    Layers,
    Library,
    Magnet,
    Map,
    MapPin,
    MessageCircle,
    MessageSquare,
    Network,
    Orbit,
    Radio,
    Rocket,
    Satellite,
    Send,
    Share2,
    Sparkles,
    Star,
    TrendingUp,
    UserPlus,
    Users,
    Zap,
} from 'lucide-react';

const ICON_MAP = {
    Activity,
    Award,
    BookOpen,
    Bookmark,
    Briefcase,
    CalendarCheck,
    CalendarDays,
    CalendarRange,
    Crown,
    GitBranch,
    Globe,
    Hexagon,
    Laptop,
    Layers,
    Library,
    Magnet,
    Map,
    MapPin,
    MessageCircle,
    MessageSquare,
    Network,
    Orbit,
    Radio,
    Rocket,
    Satellite,
    Send,
    Share2,
    Sparkles,
    Star,
    TrendingUp,
    UserPlus,
    Users,
    Zap,
};

export default function AchievementIcon({ name, className }) {
    const Icon = ICON_MAP[name] || Award;
    return <Icon className={className} />;
}
